add job for cancel running pipeline

diff --git a/seminar-3/.gitlab-ci.yml b/seminar-3/.gitlab-ci.yml
--- a/seminar-3/.gitlab-ci.yml
+++ b/seminar-3/.gitlab-ci.yml
@@ -9,6 +9,8 @@ stages:
   - test
   - deploy
   - stop
+  - stop previous jobs
+
 variables:
   IMAGE_TAG: $CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
 
@@ -119,6 +121,24 @@ deploy to production:
   when: manual
   environment:
     name: production
+
+# ------- Cancel -------
+cancel:
+  stage: stop previous jobs
+  image: everpeace/curl-jq
+  script:
+    - |
+      if [ "$CI_COMMIT_REF_NAME" == "main" ]
+        then
+          (
+            echo "Cancel old pipelines from the same branch except last"
+            OLD_PIPELINES=$( curl -s -H "PRIVATE-TOKEN: $RUNNER_TOKEN" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/pipelines?ref=${CI_COMMIT_REF_NAME}&status=running" \
+                  | jq '.[] | .id' | tail -n +2 )
+                  for pipeline in ${OLD_PIPELINES}; \
+                      do echo "Killing ${pipeline}" && \
+                        curl -s --request POST -H "PRIVATE-TOKEN: ${RUNNER_TOKEN}" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/pipelines/${pipeline}/cancel"; done
+          ) || echo "Canceling old pipelines (${OLD_PIPELINES}) failed"
+      fi
 
 pages:
   stage: deploy
